repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        args: ['--maxkb=1024']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      # Linter
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Formatter
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: mypy
        language: system
        files: \.py$
        args: [--config-file, ./pyproject.toml]
